services:
    mongodb:
        restart: always
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

    rabbitmq:
        image: rabbitmq:3.11.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "5672"]
            interval: 30s
            timeout: 10s
            retries: 3
        restart: always

volumes:
    mongodb_data:
        driver: local
